/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.Controller;
import domain.Customer;
import domain.Order;
import domain.OrderDetail;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Uffe & Mads
 */
public class MainGUIFrame extends javax.swing.JFrame {
  OrderDetail currentDetail; // denne skal laves om, kun midlertidig.
  Customer currentCustomer; // denne skal laves om, kun midlertidig.
  Order currentOrder; // denne skal laves om, kun midlertidig.
  Controller control;
    /**
     * Creates new form MainGUIFrame
     */
    public MainGUIFrame() {
        initComponents();
        control = Controller.getInstance();
        
        // VIL BLIVE LAVET AF METODE SENERE
        dropDownRes.add("Lille Stang");
        dropDownRes.add("Medium Stang");
        dropDownRes.add("Stor Stang");
        dropDownRes.add("1337 Stang");
        // VIL BLIVE LAVET AF METODE SENERE
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        createOrderTab = new javax.swing.JPanel();
        customerIdTextField = new javax.swing.JTextField();
        salesIdTextField = new javax.swing.JTextField();
        startDateTextField = new javax.swing.JTextField();
        endDateTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        createOrderButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        orderIdTextField = new javax.swing.JTextField();
        createOrderDetailsTab = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        orderIdLabel = new javax.swing.JLabel();
        addDetailsToListButton = new javax.swing.JButton();
        resourceAmountTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dropDownRes = new java.awt.Choice();
        jScrollPane1 = new javax.swing.JScrollPane();
        resourceListTextArea = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        saveListButton = new javax.swing.JButton();
        findOrderTextField = new javax.swing.JTextField();
        findOrderButton = new javax.swing.JButton();
        createCustomerTab = new javax.swing.JPanel();
        fullNameTextField = new javax.swing.JTextField();
        companyNameTextField = new javax.swing.JTextField();
        zipCodeTextField = new javax.swing.JTextField();
        adressTextFIeld = new javax.swing.JTextField();
        phoneNoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        customerIdTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        createCustomerButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listAllTextArea = new javax.swing.JTextArea();
        customerListButton = new javax.swing.JButton();
        orderListButton = new javax.swing.JButton();
        resourceListButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createOrderTab.setBackground(new java.awt.Color(204, 204, 255));

        customerIdTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        customerIdTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                customerIdTextFieldActionPerformed(evt);
            }
        });

        salesIdTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        salesIdTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                salesIdTextFieldActionPerformed(evt);
            }
        });

        startDateTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startDateTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startDateTextFieldActionPerformed(evt);
            }
        });

        endDateTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        endDateTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                endDateTextFieldActionPerformed(evt);
            }
        });

        priceTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        priceTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                priceTextFieldActionPerformed(evt);
            }
        });

        createOrderButton.setText("Opret Ordre");
        createOrderButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                createOrderButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Kunde ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Salgsmedarbejder ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Start dato:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Slut dato:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Pris:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Ordre ID:");
        jLabel12.setToolTipText("");

        orderIdTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        orderIdTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                orderIdTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createOrderTabLayout = new javax.swing.GroupLayout(createOrderTab);
        createOrderTab.setLayout(createOrderTabLayout);
        createOrderTabLayout.setHorizontalGroup(
            createOrderTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderTabLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(createOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(createOrderTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createOrderTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(createOrderTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderIdTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIdTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesIdTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        createOrderTabLayout.setVerticalGroup(
            createOrderTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderTabLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(createOrderTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(createOrderTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createOrderTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salesIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createOrderTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createOrderTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createOrderTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(84, 84, 84))
        );

        jTabbedPane2.addTab("Opret Ordre", createOrderTab);

        createOrderDetailsTab.setBackground(new java.awt.Color(204, 255, 204));

        jLabel13.setText("Ordre ID:");

        addDetailsToListButton.setText("Tilføj til listen");
        addDetailsToListButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addDetailsToListButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Antal:");

        resourceListTextArea.setEditable(false);
        resourceListTextArea.setColumns(20);
        resourceListTextArea.setRows(5);
        jScrollPane1.setViewportView(resourceListTextArea);

        jLabel15.setText("Vælg Ressource:");

        saveListButton.setText("Gem listen");

        findOrderButton.setText("Find Ordre");
        findOrderButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                findOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createOrderDetailsTabLayout = new javax.swing.GroupLayout(createOrderDetailsTab);
        createOrderDetailsTab.setLayout(createOrderDetailsTabLayout);
        createOrderDetailsTabLayout.setHorizontalGroup(
            createOrderDetailsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderDetailsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createOrderDetailsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createOrderDetailsTabLayout.createSequentialGroup()
                        .addComponent(addDetailsToListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveListButton)
                        .addGap(41, 41, 41))
                    .addGroup(createOrderDetailsTabLayout.createSequentialGroup()
                        .addGroup(createOrderDetailsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(createOrderDetailsTabLayout.createSequentialGroup()
                                .addComponent(resourceAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dropDownRes, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createOrderDetailsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(createOrderDetailsTabLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(107, 107, 107)
                                    .addComponent(jLabel15))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(createOrderDetailsTabLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(104, 104, 104)
                                    .addComponent(orderIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(createOrderDetailsTabLayout.createSequentialGroup()
                                    .addComponent(findOrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(findOrderButton))))
                        .addContainerGap(300, Short.MAX_VALUE))))
        );
        createOrderDetailsTabLayout.setVerticalGroup(
            createOrderDetailsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createOrderDetailsTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(createOrderDetailsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(createOrderDetailsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(createOrderDetailsTabLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createOrderDetailsTabLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(createOrderDetailsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(findOrderButton)
                            .addComponent(findOrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createOrderDetailsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resourceAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropDownRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(createOrderDetailsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveListButton)
                    .addComponent(addDetailsToListButton))
                .addGap(23, 23, 23))
        );

        jTabbedPane2.addTab("Tilføj Ressourcer", createOrderDetailsTab);

        createCustomerTab.setBackground(new java.awt.Color(204, 204, 204));

        fullNameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fullNameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fullNameTextFieldActionPerformed(evt);
            }
        });

        companyNameTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                companyNameTextFieldActionPerformed(evt);
            }
        });

        zipCodeTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        zipCodeTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                zipCodeTextFieldActionPerformed(evt);
            }
        });

        adressTextFIeld.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                adressTextFIeldActionPerformed(evt);
            }
        });

        phoneNoTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phoneNoTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                phoneNoTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Fulde Navn");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Firma Navn");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Post Nr.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Adresse");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Tlf. Nr.");

        customerIdTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Kunde ID");

        createCustomerButton.setText("Opret Kunde");
        createCustomerButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                createCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createCustomerTabLayout = new javax.swing.GroupLayout(createCustomerTab);
        createCustomerTab.setLayout(createCustomerTabLayout);
        createCustomerTabLayout.setHorizontalGroup(
            createCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomerTabLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(createCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createCustomerTabLayout.createSequentialGroup()
                        .addGap(0, 195, Short.MAX_VALUE)
                        .addComponent(createCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(createCustomerTabLayout.createSequentialGroup()
                        .addGroup(createCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(createCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerIdTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(fullNameTextField)
                            .addComponent(companyNameTextField)
                            .addComponent(zipCodeTextField)
                            .addComponent(phoneNoTextField)
                            .addComponent(adressTextFIeld))
                        .addContainerGap())))
        );
        createCustomerTabLayout.setVerticalGroup(
            createCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomerTabLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(createCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIdTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(companyNameTextField)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(createCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adressTextFIeld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(createCustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(createCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jTabbedPane2.addTab("Opret Kunde", createCustomerTab);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jButton1.setText("Gem i Database");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButton1)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Gem", jPanel1);

        listAllTextArea.setEditable(false);
        listAllTextArea.setColumns(20);
        listAllTextArea.setRows(5);
        jScrollPane2.setViewportView(listAllTextArea);

        customerListButton.setText("Kunder");
        customerListButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                customerListButtonActionPerformed(evt);
            }
        });

        orderListButton.setText("Ordre");
        orderListButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                orderListButtonActionPerformed(evt);
            }
        });

        resourceListButton.setText("Ressourcer");
        resourceListButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                resourceListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(customerListButton)
                        .addGap(110, 110, 110)
                        .addComponent(orderListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resourceListButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerListButton)
                    .addComponent(resourceListButton)
                    .addComponent(orderListButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Oversigt", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void endDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDateTextFieldActionPerformed

    private void startDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateTextFieldActionPerformed

    private void salesIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salesIdTextFieldActionPerformed

    private void customerIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdTextFieldActionPerformed

    private void createOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrderButtonActionPerformed
            
        Date startDate = null;
        Date endDate = null;
        if (startDateTextField.getText().length()  == 10  && 
            startDateTextField.getText().charAt(2) == '-' &&
            startDateTextField.getText().charAt(5) == '-' &&
            endDateTextField.getText().length()  == 10  && 
            endDateTextField.getText().charAt(2) == '-' &&
            endDateTextField.getText().charAt(5) == '-')
        {
            startDate = control.formatStringToDate(startDateTextField.getText());
            endDate = control.formatStringToDate(endDateTextField.getText()); 
        
            try{
        
        int correct = JOptionPane.showConfirmDialog(rootPane, "Er disse informationer korrekte? \n"
                                    + "Ordre ID:                       " + orderIdTextField.getText()
                                    + "\nKunde ID:                       " + customerIdTextField.getText()
                                    + "\nSalgsmedarbejder ID: "+ salesIdTextField.getText()
                                    + "\nStart dato:                      "+ startDateTextField.getText()
                                    + "\nSlut dato:                        " + endDateTextField.getText()
                                    + "\nPris:                                " + priceTextField.getText());
        
        if (correct == 0) {
            currentOrder = new Order(Integer.parseInt(orderIdTextField.getText()),
                                     Integer.parseInt(customerIdTextField.getText()),
                                     Integer.parseInt(salesIdTextField.getText()),
                                     false, startDate, endDate,
                                     Integer.parseInt(priceTextField.getText()));
            System.out.println("Order has been created! (remember to save it) mwehehe"
                              +"\n"+currentOrder);
        
            orderIdLabel.setText(currentOrder.getOrderID()+"");
        }
        else{
            System.out.println("Ordren blev IKKE oprettet!");
        }
        }
        catch(Exception e){
            System.out.println("Ordren blev IKKE oprettet!");
        }
        
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Dato formatet skal skrives således: DD-MM-YYYY");
        }
        
        
        
        clearOrderTabTextFields();
    }//GEN-LAST:event_createOrderButtonActionPerformed

    private void fullNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTextFieldActionPerformed

    private void companyNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyNameTextFieldActionPerformed

    private void zipCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeTextFieldActionPerformed

    private void adressTextFIeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressTextFIeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressTextFIeldActionPerformed

    private void phoneNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoTextFieldActionPerformed

    private void createCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCustomerButtonActionPerformed

         
        try{
            int correct = JOptionPane.showConfirmDialog(rootPane, "Er disse informationer korrekte? \n"
                                    + "Kunde ID: " + customerIdTextField2.getText()
                                    + "\nFulde Navn: "+ fullNameTextField.getText()
                                    + "\nFirma Navn: "+ companyNameTextField.getText()
                                    + "\nAdresse: " + adressTextFIeld.getText()
                                    + "\nPost Nr: " + zipCodeTextField.getText()
                                    + "\nTelefon Nr: " + phoneNoTextField.getText());
        if (correct == 0) {
            currentCustomer = new Customer(Integer.parseInt(customerIdTextField2.getText()),
                                           fullNameTextField.getText(),
                                           companyNameTextField.getText(),
                                           adressTextFIeld.getText(),
                                           Integer.parseInt(zipCodeTextField.getText()),
                                           Integer.parseInt(phoneNoTextField.getText()));
            System.out.println("Customer has been created! (remember to save it) mwehehe"
                              +"\n"+currentCustomer);
        }
        }
        catch(Exception e){
            System.out.println("DET GIK GALT!!!!");
        }
        
        clearCustomerTabTextFields();
    }//GEN-LAST:event_createCustomerButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (currentOrder != null) {
        control.insertOrder(currentOrder);
        }
        if(currentCustomer != null){
        control.insertCustomer(currentCustomer);
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addDetailsToListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDetailsToListButtonActionPerformed
            int resId = 0;
            if (dropDownRes.getSelectedItem().equalsIgnoreCase("Stor Stang")) 
            {
                resId = 3;
            }
            else if (dropDownRes.getSelectedItem().equalsIgnoreCase("Medium Stang")) 
            {
                resId = 2;
            }
            else if (dropDownRes.getSelectedItem().equalsIgnoreCase("Lille Stang")) 
            {
                resId = 1;
            }
            else if (dropDownRes.getSelectedItem().equalsIgnoreCase("1337 Stang")) 
            {
                resId = 4;
            }
            currentDetail = new OrderDetail(currentOrder.getOrderID(), resId, 1, 
                                            Integer.parseInt(resourceAmountTextField.getText()));
            resourceListTextArea.setText(resourceListTextArea.getText()+currentDetail+"\n");
            currentOrder.addDetail(currentDetail);
            
            // Dette er ikke en brugbar transaktion!
    }//GEN-LAST:event_addDetailsToListButtonActionPerformed

    private void findOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findOrderButtonActionPerformed
        try {
        orderIdLabel.setText(control.getOrder(Integer.parseInt(findOrderTextField.getText())).getOrderID()+"");
        currentOrder = control.getOrder(Integer.parseInt(findOrderTextField.getText()));
        } catch (Exception e) {
        }

    }//GEN-LAST:event_findOrderButtonActionPerformed

    private void orderIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderIdTextFieldActionPerformed

    private void customerListButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_customerListButtonActionPerformed
    {//GEN-HEADEREND:event_customerListButtonActionPerformed
        
        listAllTextArea.setText("");
        
        ArrayList <Customer> Customers = control.getAllCustomers();
        for (Customer Customer1 : Customers)
        {
            listAllTextArea.setText(listAllTextArea.getText()+Customer1+"\n");
        }
    }//GEN-LAST:event_customerListButtonActionPerformed

    private void resourceListButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_resourceListButtonActionPerformed
    {//GEN-HEADEREND:event_resourceListButtonActionPerformed
       
    }//GEN-LAST:event_resourceListButtonActionPerformed

    private void orderListButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_orderListButtonActionPerformed
    {//GEN-HEADEREND:event_orderListButtonActionPerformed
       listAllTextArea.setText("");
        
        ArrayList <Order> Orders = control.getAllOrders();
        for (Order Order1 : Orders)
        {
            listAllTextArea.setText(listAllTextArea.getText()+Order1+"\n");
        }
    }//GEN-LAST:event_orderListButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUIFrame().setVisible(true);
            }
        });
    }
    private void clearOrderTabTextFields(){
        orderIdTextField.setText("");
        customerIdTextField.setText("");
        salesIdTextField.setText("");
        startDateTextField.setText("");
        endDateTextField.setText("");
        priceTextField.setText("");
    }
    private void clearCustomerTabTextFields(){
        customerIdTextField2.setText("");
        fullNameTextField.setText("");
        companyNameTextField.setText("");
        adressTextFIeld.setText("");
        zipCodeTextField.setText("");
        phoneNoTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDetailsToListButton;
    private javax.swing.JTextField adressTextFIeld;
    private javax.swing.JTextField companyNameTextField;
    private javax.swing.JButton createCustomerButton;
    private javax.swing.JPanel createCustomerTab;
    private javax.swing.JButton createOrderButton;
    private javax.swing.JPanel createOrderDetailsTab;
    private javax.swing.JPanel createOrderTab;
    private javax.swing.JTextField customerIdTextField;
    private javax.swing.JTextField customerIdTextField2;
    private javax.swing.JButton customerListButton;
    private java.awt.Choice dropDownRes;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JButton findOrderButton;
    private javax.swing.JTextField findOrderTextField;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea listAllTextArea;
    private javax.swing.JLabel orderIdLabel;
    private javax.swing.JTextField orderIdTextField;
    private javax.swing.JButton orderListButton;
    private javax.swing.JTextField phoneNoTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField resourceAmountTextField;
    private javax.swing.JButton resourceListButton;
    private javax.swing.JTextArea resourceListTextArea;
    private javax.swing.JTextField salesIdTextField;
    private javax.swing.JButton saveListButton;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables
}
